#ifndef CONSTANTS_HH
#define CONSTANTS_HH

#define ASSETS_PATH "assets/"
#define ASSET_SPRITES_PATH "Sprites/"
#define ASSET_SPRITE_LOADING_SCREEN "Spr_LoadingScreen.png"
#define ASSET_SPRITE_MAP_BG "Spr_Map_BG.png"
#define ASSET_SPRITE_MAP_MG "Spr_Map_MG.png"
#define ASSET_SPRITE_MAP_FG "Spr_Map_FG.png"
#define ASSET_SPRITE_BOMB_BODY "Spr_Bomb_Body.png"
#define ASSET_SPRITE_BOMB_DECO "Spr_Bomb_Deco.png"
#define ASSET_SPRITE_BOMB_FUSE "Spr_Bomb_Fuse.png"
#define ASSET_SPRITE_BOMBHOUSE "Spr_BombHouse.png"
#define ASSET_SPRITE_BOMBHOUSE_SCREEN "Spr_BombHouse_Screen.png"
#define ASSET_SPRITE_EXPLOSION "Spr_Explosion.png"
#define ASSET_SPRITE_EXPLOSION_PROPS "Spr_Explosion_Props.png"
#define ASSET_SPRITE_GAMEOVER_OVERLAY "Spr_GameOver_Overlay.png"
#define ASSET_SPRITE_PIPE_VALVE "Spr_Pipe_Valve.png"
#define ASSET_SPRITE_PIPE_VALVE_INDICATOR "Spr_Pipe_Valve_Indicator.png"
#define ASSET_SPRITE_STEAM_CLOUD "Spr_SteamCloud.png"
#define ASSET_SPRITE_STEAM_EMITTER "Spr_SteamEmitter.png"
#define ASSET_SPRITE_STEAM_INDICATOR_BASE "Spr_SteamIndicator_Base.png"
#define ASSET_SPRITE_STEAM_INDICATOR_NEEDLE "Spr_SteamIndicator_Needle.png"
#define ASSET_SPRITE_SMALL_SCREEN "Spr_SmallScreen.png"
#define ASSET_SPRITE_SCREEN_NUMBERS "Spr_ScreenNumbers.png"
#define ASSET_SPRITE_MENU_INFO "Spr_MenuInfo.png"
#define ASSET_SPRITE_PAUSE_MENU "Spr_PauseMenu.png"
#define ASSET_SPRITE_PAUSE_BUTTON "Spr_PauseButton.png"

#define ASSET_SOUNDS_PATH "Sounds/"
#define ASSET_SOUND_BOMB_STEP_SOUNDS 16
#define ASSET_SOUND_BOMB_STEP_PREFIX "Bomb_Step_"
#define ASSET_SOUND_BOMB_STEP_SUFFIX ".wav"
#define ASSET_SOUND_BOMB_COLLISION_SOUNDS 10
#define ASSET_SOUND_BOMB_COLLISION_PREFIX "Bomb_Collision_"
#define ASSET_SOUND_BOMB_COLLISION_SUFFIX ".wav"
#define ASSET_SOUND_BOMB_WINDUP_LOOP "Bomb_WindUp_Loop.wav"
#define ASSET_SOUND_BOMB_FUSE_LOOP "Bomb_Fuse_Loop.wav"
#define ASSET_SOUND_BOMB_EXPLOSION "Bomb_Explosion_000.wav"
#define ASSET_SOUND_BOMB_GRABBED "Bomb_Grabbed.mp3"
#define ASSET_SOUND_BOMB_RELEASED_BOMB_HOUSE "Bomb_Released_BombHouse.mp3"
#define ASSET_SOUND_BOMB_RELEASED_METAL "Bomb_Released_Metal.mp3"
#define ASSET_SOUND_BOMB_WARNING "Bomb_Warning.wav"
#define ASSET_SOUND_BOMBHOUSE_TRANSITION_FLASH "BombHouse_Transition_Flash.mp3"
#define ASSET_SOUND_PIPE_STEAM_LOOP "Pipe_Steam_Loop.mp3"
#define ASSET_SOUND_PIPE_STEAM_HISS_LOOP "Pipe_Steam_Hiss_Loop.mp3"
#define ASSET_SOUND_PIPE_VALVE_ROTATE_SOUNDS 9
#define ASSET_SOUND_PIPE_VALVE_ROTATE_SOUND_FILES 3
#define ASSET_SOUND_PIPE_VALVE_ROTATE_PREFIX "Pipe_ValveRotate_"
#define ASSET_SOUND_PIPE_VALVE_ROTATE_SUFFIX ".mp3"
#define ASSET_SOUND_POINT_SOUNDS 5
#define ASSET_SOUND_POINT "Point.mp3"
#define ASSET_SOUND_POINT_TALLY "PointTally.mp3"
#define ASSET_SOUND_APPLAUSE "Applause.mp3"
#define ASSET_SOUND_DRAMATIC_DRUM "DramaticDrum.mp3"
#define ASSET_SOUND_GAMEOVER_ALERT "GameOver_Alert.wav"
#define ASSET_SOUND_GAMEOVER_JINGLE "GameOver_Jingle.wav"
#define ASSET_SOUND_POINT_TALLY_END "PointTallyEnd.mp3"
#define ASSET_SOUND_POINT_TALLY_END_HIGHSCORE "PointTallyEnd_Highscore.mp3"
#define ASSET_SOUND_MUSIC "Music_000.mp3"
#define ASSET_SOUND_FACTORY_AMBIENCE "Factory_Ambience.mp3"

#define ASSET_SOUND_MUSIC_LOOP_START 15.132f
#define ASSET_SOUND_MUSIC_LOOP_END 152.032f
#define ASSET_SOUND_MUSIC_LOOP_LENGTH (ASSET_SOUND_MUSIC_LOOP_END - ASSET_SOUND_MUSIC_LOOP_START)

#define ASSET_SOUND_FACTORY_AMBIENCE_LOOP_START 0.1f
#define ASSET_SOUND_FACTORY_AMBIENCE_LOOP_END 20.00f
#define ASSET_SOUND_FACTORY_AMBIENCE_LOOP_LENGTH (ASSET_SOUND_FACTORY_AMBIENCE_LOOP_END - ASSET_SOUND_FACTORY_AMBIENCE_LOOP_START)

#define LOADING_SCREEN_SPRITE_SIZE 368

#define SAVE_FILE_PATH "./save_data.bbw"
#define HIGHSCORE_DEFAULT 30

#define MAP_SPRTE_SIZE 1024
#define MAP_BG_SPRITE_SIZE_X 2560
#define MAP_BG_SPRITE_SIZE_Y 1280
#define MAP_MG_SPRITE_SIZE_X 1196
#define MAP_MG_SPRITE_SIZE_Y 320
#define MAP_FG_SPRITE_SIZE_X 2560
#define MAP_FG_SPRITE_SIZE_Y 456
#define MAP_COORD_SIZE 1000
#define MAP_COORD_RADIUS (MAP_COORD_SIZE / 2)
#define MAP_COORD_HORIZONTAL_MIN_VIEWABLE_SIZE 525
#define MAP_BG_COORD_SIZE_X (MAP_COORD_SIZE * ((float)MAP_BG_SPRITE_SIZE_X / (float)MAP_SPRTE_SIZE))
#define MAP_BG_COORD_SIZE_Y (MAP_COORD_SIZE * ((float)MAP_BG_SPRITE_SIZE_Y / (float)MAP_SPRTE_SIZE))
#define MAP_BG_COORD_RADIUS_X (MAP_BG_COORD_SIZE_X / 2.0f)
#define MAP_BG_COORD_RADIUS_Y (MAP_BG_COORD_SIZE_Y / 2.0f)
#define MAP_MG_COORD_SIZE_X (MAP_COORD_SIZE * ((float)MAP_MG_SPRITE_SIZE_X / (float)MAP_SPRTE_SIZE))
#define MAP_MG_COORD_SIZE_Y (MAP_COORD_SIZE * ((float)MAP_MG_SPRITE_SIZE_Y / (float)MAP_SPRTE_SIZE))
#define MAP_FG_COORD_SIZE_X (MAP_COORD_SIZE * ((float)MAP_FG_SPRITE_SIZE_X / (float)MAP_SPRTE_SIZE))
#define MAP_FG_COORD_SIZE_Y (MAP_COORD_SIZE * ((float)MAP_FG_SPRITE_SIZE_Y / (float)MAP_SPRTE_SIZE))

#define DEBUG_DRAW_MAP_BOUNDS false
#define DEBUG_DRAW_FPS false

#define SPRTE_TO_COORD(a) ((float)(a) / (float)(MAP_SPRTE_SIZE) * (MAP_COORD_SIZE) - (MAP_COORD_RADIUS))

#define MAP_COORD_HOR_MIN -1200
#define MAP_COORD_HOR_MAX 1200

#define MAP_SPRTE_VER_MIN 200
#define MAP_SPRTE_VER_MAX 720
#define MAP_COORD_VER_MIN SPRTE_TO_COORD(MAP_SPRTE_VER_MIN)
#define MAP_COORD_VER_MAX SPRTE_TO_COORD(MAP_SPRTE_VER_MAX)

#define DEBUG_SPAWN_MAX_DEVICE_BOMBS_START false

#define ROUND_BOMB_SPAWN_TIME_START 1
#define ROUND_BOMB_SPAWN_TIME_INCREMENT 0.125f
#define ROUND_BOMB_SPAWN_TIME_MIN .75f
#define ROUND_MAX_BOMBS_START 2
#define ROUND_MAX_BOMBS_INCREMENT 0.1f
#define ROUND_BOMB_HOUSE_MUSIC_CHANGE_TIMES 11
const float ROUND_BOMB_HOUSE_MUSIC_CHANGE_TIMES_ARRAY[ROUND_BOMB_HOUSE_MUSIC_CHANGE_TIMES] = { 13.0f, 27.4f, 41.75f, 55.75f, 70.0f, 84.25f, 98.5f, 112.75f, 127.0f, 141.25f, 150.0f };
#define ROUND_BLUE_BOMB_SPAWN_TIME_START 50.f
#define ROUND_GREEN_BOMB_SPAWN_TIME_START 120.f
#define ROUND_TIME_FOR_DRAMATIC_DRUM 3.f

#define ROUND_DEVICE_MAX_BOMBS_MIN 2
#define ROUND_DEVICE_MAX_BOMBS_MAX 50

#define DEBUG_BOMBHOUSE_TYPE_DRAW false

#define BOMBHOUSE_LENIENCE_TIME 8.0f

#define BOMBHOUSE_ANIMATION_FRAMES 11
#define BOMBHOUSE_ANIMATION_SPEED 25

#define BOMBHOUSE_SPRTE_HOR_MIN 453
#define BOMBHOUSE_SPRTE_HOR_MAX 571
#define BOMBHOUSE_SPRITE_SIZE 256
#define BOMBHOUSE_COORD_HOR_MIN SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MIN)
#define BOMBHOUSE_COORD_HOR_MAX SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MAX)
#define BOMBHOUSE_SPRTE_BOT_VER_POS MAP_SPRTE_SIZE - 240
#define BOMBHOUSE_SPRTE_TOP_VER_POS 186
#define BOMBHOUSE_COORD_BOT_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_BOT_VER_POS)
#define BOMBHOUSE_COORD_TOP_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_TOP_VER_POS)
#define BOMBHOUSE_SCREEN_SPRITE_SIZE 128
#define BOMBHOUSE_SCREEN_COORD_SIZE 122
#define BOMBHOUSE_SCREEN_TOP_SPRTE_X 678
#define BOMBHOUSE_SCREEN_TOP_SPRTE_Y 85
#define BOMBHOUSE_SCREEN_TOP_COORD_X SPRTE_TO_COORD(BOMBHOUSE_SCREEN_TOP_SPRTE_X)
#define BOMBHOUSE_SCREEN_TOP_COORD_Y SPRTE_TO_COORD(BOMBHOUSE_SCREEN_TOP_SPRTE_Y)
#define BOMBHOUSE_SCREEN_BOT_SPRTE_X 347
#define BOMBHOUSE_SCREEN_BOT_SPRTE_Y 907
#define BOMBHOUSE_SCREEN_BOT_COORD_X SPRTE_TO_COORD(BOMBHOUSE_SCREEN_BOT_SPRTE_X)
#define BOMBHOUSE_SCREEN_BOT_COORD_Y SPRTE_TO_COORD(BOMBHOUSE_SCREEN_BOT_SPRTE_Y)
#define BOMBHOUSE_SCREEN_TEXT_OFFSET_X -63
#define BOMBHOUSE_SCREEN_TRANSITION_START_PIXEL 4
#define BOMBHOUSE_SCREEN_TRANSITION_FLASH_COUNT 4
#define BOMBHOUSE_SCREEN_TRANSITION_FLASH_BEAT_DURATION (60.0f / 135.0f)
#define BOMBHOUSE_SCREEN_TRANSITION_FLASH_CYCLE_BEATS 1.0f
#define BOMBHOUSE_SCREEN_TRANSITION_FLASH_DUTY_CYCLE 0.5f
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_PLAY 8
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_INFO 14
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_REVIVE 13
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_NOT_REVIVE 9
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_SCORE 10
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_HIGHSCORE 12
#define BOMBHOUSE_SCREEN_SPRITE_INDEX_HIGHSCORE_NEW 11

#define BOMB_TYPE_COUNT 9
enum BombType { BOMB_BLACK, BOMB_RED, BOMB_BLUE, BOMB_GREEN, BOMB_ABOUT_TO_EXPLODE, BOMB_INVALID, BOMB_MENU, BOMB_REVIVE, BOMB_POINT_TALLY };

#define BOMB_CHANCE_TO_SPAWN_RANDOM_COLOR 10

#define DEBUG_BOMB_HITBOX_DRAW false

#define BOMB_EXPLODE_TIME 45.0f
#define BOMB_EXPLODE_FUSE_TIME 20.0f
#define BOMB_EXPLODE_TIME_REVIVE 10.0f

#define BOMB_SPRITE_SIZE 256
#define BOMB_SPRITE_HITBOX_SIZE 100
#define BOMB_FUSE_SPRITE_SIZE 64
#define BOMB_FUSE_SPRITES 15
#define BOMB_FUSE_SPRITE_OFFSET_Y_MAX -60
#define BOMB_FUSE_SPRITE_OFFSET_Y_MIN -40

#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MIN { MAP_COORD_HOR_MIN, MAP_COORD_VER_MIN }
#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MAX { MAP_COORD_HOR_MAX, MAP_COORD_VER_MAX }

#define BOMB_RELEASED_TOP 1
#define BOMB_RELEASED_BOT 2
#define BOMB_RELEASED_DEF 3

#define BOMB_PLACED_TOP 0
#define BOMB_PLACED_BOT 1

#define BOMB_SPAWN_POS_OFFSET 20

#define BOMB_ANIM_INDEX_WALK_BOT_LEFT 0
#define BOMB_ANIM_INDEX_WALK_BOT_RIGHT 1
#define BOMB_ANIM_INDEX_WALK_TOP_RIGHT 2
#define BOMB_ANIM_INDEX_WALK_TOP_LEFT 3
#define BOMB_ANIM_INDEX_GRABBED 4
#define BOMB_ANIM_INDEX_PLACED_BOT 5
#define BOMB_ANIM_INDEX_PLACED_TOP 6

#define BOMB_WINDUP_LOOP_SOUND_VOLUME 0.1f
#define BOMB_FUSE_LOOP_SOUND_VOLUME 0.7f
#define BOMB_FUSE_LOOP_TIME 5.9f

#define BOMB_STEP_SOUND_ANIM_FRAME_001 9
#define BOMB_STEP_SOUND_ANIM_FRAME_002 23
#define BOMB_MUSIC_TIME_OFFSET 0.25f

#define BOMB_GRAB_MOUSE_SCALE_INDEX 2.f
#define BOMB_GRAB_MOUSE_HITBOX_OFFSET_Y 10
#define BOMB_GRABBED_SCALE_INDEX 1.25f

#define EXPLOSION_SPRITE_SIZE 256
#define EXPLOSION_ANIMATION_SPRITES 60
#define EXPLOSION_SIZE 320
#define EXPLOSION_DURATION 2.0f

#define EXPLOSION_PROPS_NUMBER 5
#define EXPLOSION_PROPS_SPRITE_SIZE 64

#define SCREEN_SHAKE_MAX_TIME 2.0f
#define SCREEN_SHAKE_MAX_ROTATION_DEGREES 3.0f
#define SCREEN_SHAKE_MAX_FREQUENCY 25.0f
#define SCREEN_SHAKE_DECAY_RATE  1.8f
#define EXPLOSION_SCREEN_SHAKE_TIME 2.0f
#define DRAMATIC_DRUM_SCREEN_SHAKE_TIME 1.0f

#define PAUSE_RESUME_COUNTDOWN_TICKS 3
#define PAUSE_RESUME_COUNTDOWN_TICK_TIME (60.0f / 135.0f)

#define GAMEOVER_CUTSCENE_TIME 3.0f
#define GAMEOVER_OVERLAY_SPRTE_SIZE 128
#define GAMEOVER_OVERLAY_SPRTE_COLOR {0,0,0,200}

#define GAMEOVER_OVERLAY_CUTSCENE_TIME 3.5f
#define GAMEOVER_OVERLAY_CUTSCENE_FADEIN_TIME 0.25f
#define GAMEOVER_OVERLAY_CUTSCENE_SIZE_START 2343.75f
#define GAMEOVER_OVERLAY_CUTSCENE_SIZE_END 138.875f
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_TIME 2.75f
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_SCALE 4.375f
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_VELOCITY 5.f

#define GAMEOVER_RESTART_TIME 5.0f

#define POINT_TALLY_INCREMENT_SPEED 40.0f
#define POINT_TALLY_DONE_TIME_MIN 3.0f
#define POINT_TALLY_DONE_TIME_MAX 20.0f
#define POINT_TALLY_SOUND_POINT_INTERVAL 1
#define POINT_TALLY_SKIP_CLICKS 5

#define SMALL_SCREEN_SPRITE_WIDTH 160
#define SMALL_SCREEN_SPRITE_HEIGHT 73
#define SCREEN_NUMBER_SPRITE_WIDTH  24
#define SCREEN_NUMBER_SPRITE_HEIGHT 40
#define SMALL_SCREEN_POSITION_X_OFFSET -162
#define SMALL_SCREEN_POSITION_Y 425
#define SMALL_SCREEN_NUMBER_POSITION_OFFSET_X 15
#define SMALL_SCREEN_NUMBER_POSITION_OFFSET_Y 16.5f
#define SMALL_NUMBER_YELLOW_COLOR { 255, 251, 155, 255 }

#define PIPE_VALVE_SPRITE_SIZE 108
#define PIPE_VALVE_INDICATOR_SPRITE_SIZE 150
#define PIPE_STEAM_MIN_VALUE 0.0f
#define PIPE_STEAM_MAX_VALUE 100.0f
#define PIPE_POSITION { -203, -415 }
#define PIPE_VALVE_GRAB_RADIUS 200.0f
#define PIPE_STEAM_INCREMENT_SPEED 0.5f
#define PIPE_STEAM_DECREMENT_SPEED 8.0f
#define PIPE_STEAM_SPAWN_THRESHOLD 50.0f
#define PIPE_STEAM_SPAWN_TIME 0.5f
#define PIPE_VALVE_INDICATOR_ROTATION_SPEED -150.0f
#define PIPE_STEAM_MAX_TIMER_THRESHOLD 10.0f
#define PIPE_VALVE_INDICATOR_STEAM_DISAPPEAR_THRESHOLD 80.0f
#define PIPE_VALVE_INDICATOR_COLOR_1 { 255, 150, 0, 255 }
#define PIPE_VALVE_INDICATOR_COLOR_2 { 255, 255, 0, 255 }
#define PIPE_VALVE_INDICATOR_COLOR_CYCLE_TIME 1.0f

#define PIPE_STEAM_INDICATOR_BASE_SPRITE_SIZE_X 76
#define PIPE_STEAM_INDICATOR_BASE_SPRITE_SIZE_Y 57
#define PIPE_STEAM_INDICATOR_BASE_SPRITE_OFFSET_X 74
#define PIPE_STEAM_INDICATOR_BASE_SPRITE_OFFSET_Y -80
#define PIPE_STEAM_INDICATOR_NEEDLE_SPRITE_SIZE 55
#define PIPE_STEAM_INDICATOR_NEEDLE_OFFSET_X 47
#define PIPE_STEAM_INDICATOR_NEEDLE_OFFSET_Y 30
#define PIPE_STEAM_INDICATOR_NEEDLE_ANGLE_MIN 225.0f
#define PIPE_STEAM_INDICATOR_NEEDLE_ANGLE_MAX 495.0f

#define DEBUG_PIPE_USE_START_VALUE false
#define DEBUG_PIPE_START_VALUE 100.0f
#define DEBUG_PIPE_DRAW_GRAB_RADIUS false
#define DEBUG_PIPE_DRAW_STEAM_VALUE false

#define PIPE_STEAM_CLOUD_LIFETIME 10.0f
#define PIPE_STEAM_CLOUD_ALPHA_MIN 0.0f
#define PIPE_STEAM_CLOUD_ALPHA_MAX 1.0f

#define PIPE_STEAM_CLOUD_SPRITE_SIZE 128
#define PIPE_STEAM_CLOUD_COORD_SIZE_MIN 256
#define PIPE_STEAM_CLOUD_COORD_SIZE_MAX 512
#define PIPE_STEAM_CLOUD_FRAMES 19
#define PIPE_STEAM_CLOUD_ANIMATION_SPEED_MIN 15.0f
#define PIPE_STEAM_CLOUD_ANIMATION_SPEED_MAX 30.0f
#define PIPE_STEAM_CLOUD_POSITION_Y_MIN -40
#define PIPE_STEAM_CLOUD_POSITION_Y_MAX 350

#define PIPE_STEAM_EMITTER_SPRITE_SIZE_X 184
#define PIPE_STEAM_EMITTER_SPRITE_SIZE_Y 64
#define PIPE_STEAM_EMITTER_SPRITES 26
#define PIPE_STEAM_EMITTER_ANIMATION_SPEED 45.0f
#define PIPE_STEAM_EMITTER_POSITION_X -95
#define PIPE_STEAM_EMITTER_POSITION_Y -205
#define PIPE_STEAM_EMITTER_ROTATION -90.0f

#define PIPE_STEAM_SOUND_STEAM_VALUE_MIN 50.0f
#define PIPE_STEAM_SOUND_STEAM_VALUE_MAX 80.0f
#define PIPE_STEAM_HISS_SOUND_STEAM_VALUE_MIN 75.0f
#define PIPE_STEAM_HISS_SOUND_STEAM_VALUE_MAX 100.0f

#define DEBUG_MENU_INFO_DRAW_BUTTON_BOUNDS false

#define MENU_INFO_SPRITE_SIZE_X 416
#define MENU_INFO_SPRITE_SIZE_Y 544
#define MENU_INFO_SPRITE_POSITION_X -208
#define MENU_INFO_SPRITE_POSITION_Y -297
#define MENU_INFO_INFO_SIZE_Y 392
#define MENU_INFO_BUTTON_SIZE_X 136
#define MENU_INFO_BUTTON_SIZE_Y 72
#define MENU_INFO_BUTTON_NEXT_OFFSET_X 56
#define MENU_INFO_BUTTON_NEXT_OFFSET_Y 416
#define MENU_INFO_BUTTON_EXIT_OFFSET_X 224
#define MENU_INFO_BUTTON_EXIT_OFFSET_Y 416
#define MENU_INFO_PAGES 3

#define DEBUG_PAUSE_MENU_DRAW_BUTTON_BOUNDS false

#define PAUSE_MENU_SPRITE_SIZE_X 416
#define PAUSE_MENU_SPRITE_SIZE_Y 544
#define PAUSE_MENU_SPRITE_POSITION_X -208
#define PAUSE_MENU_SPRITE_POSITION_Y -297
#define PAUSE_RESUMING_SPRITE_POSITION_Y -75
#define PAUSE_MENU_DECO_VARIANTS 3
#define PAUSE_MENU_DECO_SIZE_Y 256
#define PAUSE_MENU_BUTTON_SIZE_X 144
#define PAUSE_MENU_BUTTON_SIZE_Y 72
#define PAUSE_MENU_RESUME_BUTTON_OFFSET_X 137
#define PAUSE_MENU_RESUME_BUTTON_OFFSET_Y 304
#define PAUSE_MENU_EXIT_BUTTON_OFFSET_X 137
#define PAUSE_MENU_EXIT_BUTTON_OFFSET_Y 417

#define PAUSE_BUTTON_SPRITE_SIZE_X 96
#define PAUSE_BUTTON_SPRITE_SIZE_Y 73
#define PAUSE_BUTTON_POSITION_X_OFFSET -98
#define PAUSE_BUTTON_POSITION_Y 350

#endif